// This file is auto-generated by the gol tool. Do not edit manually.
// To regenerate: cargo run --bin gol -- generate-metadata -o path/to/output.ts --blob-map path/to/blob-mapping.json
//
// To get real blob IDs:
// 1. Run: cargo run --bin gol -- create-puzzles
// 2. For each puzzle file, run: linera publish-data-blob <puzzle_name>_puzzle.bcs
// 3. Create a blob mapping JSON file and use --blob-map option

import { PuzzleMetadata, DifficultyLevel } from "@/lib/types/puzzle.types";

// Re-export for backward compatibility
export type { PuzzleMetadata } from "@/lib/types/puzzle.types";

export const KNOWN_PUZZLES: PuzzleMetadata[] = [
  {
    id: "c02d9a93e161480fcc0cfca3675dfc0345d3f9f16f8a3abca44cf00bd441c839",
    title: "Block Formation",
    summary: "Create a stable 2x2 block pattern in the center of the board",
    difficulty: "EASY",
    size: 8,
  },
  {
    id: "7b48b2ae0b618298b9163b1ddab1a1310de9c650f9a323c2e7cffe3b374f6d38",
    title: "Beehive Formation",
    summary: "Create a stable beehive pattern (6-cell hexagonal shape)",
    difficulty: "EASY",
    size: 9,
  },
  {
    id: "b8f70fe0160a6704edc6e4ec060d914d10d5d3dcf0463030c26b0f2d7b0e9d8f",
    title: "Loaf Formation",
    summary: "Create a stable loaf pattern (7-cell bread loaf shape)",
    difficulty: "EASY",
    size: 10,
  },
  {
    id: "50c6d5d26874b6b2a93980d95f70997518eea55982c530696f0b94c046880ec5",
    title: "Boat Formation",
    summary: "Create a stable boat pattern (5-cell boat shape)",
    difficulty: "EASY",
    size: 8,
  },
  {
    id: "ef0c0a69ccae1622bf953ea469284be907f0341944684c9567a077b46f677ed7",
    title: "Tub Formation",
    summary: "Create a stable tub pattern (4-cell hollow square)",
    difficulty: "EASY",
    size: 7,
  },
  {
    id: "2174fa9903388f11b3a295078e897aa7f439deb90946755ed88400eb729927cb",
    title: "Blinker Formation",
    summary: "Create a blinker oscillator pattern (3-cell vertical line that oscillates)",
    difficulty: "EASY",
    size: 7,
  },
  {
    id: "1855ca2baf397897389cd307b49598afb177ce64ecc46812282ec63929c9a3e3",
    title: "Beacon Formation",
    summary: "Create a beacon oscillator pattern (two 2x2 blocks that blink diagonally)",
    difficulty: "EASY",
    size: 8,
  },
  {
    id: "607baa613a4bcc50d2a11e0b8135625603e65deec325f67feb724ccb13851b2c",
    title: "Clock Formation",
    summary: "Create a clock oscillator pattern (period-4 oscillator)",
    difficulty: "MEDIUM",
    size: 8,
  },
  {
    id: "e7de932762b0a6a27d29097f20caa0084c87a61fb6e21d5f49cc88c1e5542479",
    title: "Robot face",
    summary: "Create a robot-like face from very few cells",
    difficulty: "MEDIUM",
    size: 60,
  },
];

// Helper to get puzzle by ID
export function getPuzzleMetadata(id: string): PuzzleMetadata | undefined {
  return KNOWN_PUZZLES.find((puzzle) => puzzle.id === id);
}

// Helper to get puzzles by difficulty
export function getPuzzlesByDifficulty(difficulty: DifficultyLevel): PuzzleMetadata[] {
  return KNOWN_PUZZLES.filter((puzzle) => puzzle.difficulty === difficulty);
}
