// This file is auto-generated by the gol tool. Do not edit manually.
// To regenerate: cargo run --bin gol -- generate-metadata -o path/to/output.ts --blob-map path/to/blob-mapping.json
//
// To get real blob IDs:
// 1. Run: cargo run --bin gol -- create-puzzles
// 2. For each puzzle file, run: linera publish-data-blob <puzzle_name>_puzzle.bcs
// 3. Create a blob mapping JSON file and use --blob-map option

import { PuzzleMetadata, DifficultyLevel } from "@/lib/types/puzzle.types";

// Re-export for backward compatibility
export type { PuzzleMetadata } from "@/lib/types/puzzle.types";

export const KNOWN_PUZZLES: PuzzleMetadata[] = [
  {
    id: "a61b755ae3f00dffc49b3188d3615979b1cfa90ec302715974ce3b55c3b1fbbd",
    title: "Block",
    summary: "Create a stable 2x2 block pattern in the center of the board",
    difficulty: "EASY",
    size: 8,
  },
  {
    id: "bc51b1042201dbc52b862229b943cb5f4e6447b2b552c5085304b9fa1136a4bf",
    title: "Beehive",
    summary: "Create a stable beehive pattern (6-cell hexagonal shape)",
    difficulty: "EASY",
    size: 9,
  },
  {
    id: "ca3b41ae5250de1d744430b248de5a1dede98c02ba134875bb32df9191b1b087",
    title: "Loaf",
    summary: "Create a stable loaf pattern (7-cell bread loaf shape)",
    difficulty: "EASY",
    size: 10,
  },
  {
    id: "b555b0ad298b57d6db68d8d3150a5abdbe2dc58423c486355e0c48c92cac41b7",
    title: "Boat",
    summary: "Create a stable boat pattern (5-cell boat shape)",
    difficulty: "EASY",
    size: 8,
  },
  {
    id: "110ed8cae50b1abaeadb523207698f2c4d489e0db1b720aae91c7b86829bbcdd",
    title: "Tub",
    summary: "Create a stable tub pattern (4-cell hollow square)",
    difficulty: "EASY",
    size: 7,
  },
  {
    id: "2d584161ea7bf1876b64826e566592e85ddac1eef121bc9367188c6cfd8962f7",
    title: "Blinker",
    summary: "Create a blinker oscillator pattern (3-cell vertical line that oscillates)",
    difficulty: "EASY",
    size: 7,
  },
  {
    id: "7cb3305b44c20632c0938bfb3e65d69c2b52c32463575028977c6b87e19c25da",
    title: "Beacon",
    summary: "Create a beacon oscillator pattern (two 2x2 blocks that blink diagonally)",
    difficulty: "EASY",
    size: 8,
  },
  {
    id: "61897c9a6177cba237ba32b7c2b5794a92ee4a735180360f4802296bfe9c4cab",
    title: "Clock",
    summary: "Create a clock oscillator pattern (period-4 oscillator)",
    difficulty: "EASY",
    size: 8,
  },
  {
    id: "e4eebf357881f200ffd79f9310d19778e3e9ee7e98c40113ae89675d1d5a6143",
    title: "Glider Migration",
    summary: "Guide a glider from the top-left square to the bottom-right square",
    difficulty: "EASY",
    size: 16,
  },
  {
    id: "b8b3141d3814b078f31249c9cbf4b4a7e5f62659a32f944e9864117826647ca0",
    title: "Four blinkers",
    summary: "Create four blinkers from very few cells",
    difficulty: "EASY",
    size: 16,
  },
];

// Helper to get puzzle by ID
export function getPuzzleMetadata(id: string): PuzzleMetadata | undefined {
  return KNOWN_PUZZLES.find((puzzle) => puzzle.id === id);
}

// Helper to get puzzles by difficulty
export function getPuzzlesByDifficulty(difficulty: DifficultyLevel): PuzzleMetadata[] {
  return KNOWN_PUZZLES.filter((puzzle) => puzzle.difficulty === difficulty);
}
